### PR TITLE
Github action to comment on pull requests automatically

### LINKED ISSUE #5: [FEAT] Add a Github Action Bot
- Whenever a PR is created there should be a automated message to the user, something like this:

image

- When a PR is merged there should be a Thankyou message by the bot. For example: - `Thankyou @username for your contribution`. You can improvise the message.

### PR DESCRIPTION
**Pull request by Mews**
Closes #5 

**Changes**
Added two workflow files which get run when a pr is opened and closed respectively.
The comments that get added to the pr are as seen bellow.

Opening:
image

Closing:
image

### CODE REVIEW

**Review by jatiinyadav — APPROVED** [review]

**Comment by jatiinyadav** [comment]
@Mews Can you please provide your email? I need to update your score.

**Comment by Mews** [comment]
Its ar754456@gmail.com

**Comment by jatiinyadav** [comment]
> Its [ar754456@gmail.com](mailto:ar754456@gmail.com)

Is this the same email you used to registered in VSOC?

**Comment by Mews** [comment]
I dont know what vsoc is :P

**Comment by jatiinyadav** [comment]
Oh okay, actually this project was a part of [VSOC](https://www.vsoc.tech/), so I thought you are contributor from the program :)

**Comment by Mews** [comment]
Oh no I'm not haha I found your issue here https://goodfirstissues.com/ :P

**Pull request merged**
